### ISSUE TITLE
No support for non-interpolated images.

### ISSUE THREAD

**Issue by VisualMelon** [oxyplot/oxyplot-avalonia#18]
The `interpolate` parameter of `CanvasRenderContext.DrawImage` ([code](https://github.com/oxyplot/oxyplot-avalonia/blob/master/Source/OxyPlot.Avalonia/CanvasRenderContext.cs#L598)) is ignored. The effect can be seen in the matrix examples:

Screenshot from the OxyPlot-Avalonia example browser, example Custom Series > Design Structure Matrix:

![image](https://user-images.githubusercontent.com/5646475/82903273-a1e06e80-9f58-11ea-9440-112a1d2dfc96.png)

This should appear like this (from OxyPlot.WindowsForms example browser):

![image](https://user-images.githubusercontent.com/5646475/82903643-2632f180-9f59-11ea-8ed8-1764f22610f1.png)

(A workaround for heatmaps is to use `HeatMapRenderMethod.Rectangles`)

**Comment by kekekeks** [comment]
`Image` control interpolation mode can be controlled via `RenderOptions.BitmapInterpolationMode` attached property.

**Comment by VisualMelon** [comment]
@kekekeks thanks, I'll look into sorting out a PR.
