### ISSUE TITLE
UI freezing on linux-arm 

### ISSUE THREAD

**Issue by Naim-h** [oxyplot/oxyplot-avalonia#21]
I have Avalonia project and try to run chart with oxyplot-avalonia on it,it works well on windows but when I publish it to run on linux-arm (I used ARM Cortex-A9 embedded device), the page which I use chart on it become freeze(without any exception on the output).
as I know it freezes when it try to render the chart, because if I don't pass DataPoint to it , the page works as usual.

**Comment by VisualMelon** [comment]
Has this been resolved?
