### ISSUE TITLE
OHLC series

### ISSUE THREAD

**Issue by apkrymov** [oxyplot/oxyplot-avalonia#24]
Are oxyplot-avalonia OHLC time-series (candlestick) currently supported?

**Comment by VisualMelon** [comment]
High/Low and CandleStick series are both supported in OxyPlot. There don't seem to be any particular issues with their support in OxyPlot-Avalonia. See the [example library](https://github.com/oxyplot/oxyplot/tree/develop/Source/Examples/ExampleLibrary/Series) for examples.

Feel free to re-open if you have a particular concern.
