### ISSUE TITLE
chinese characters unable to display in title

### ISSUE THREAD

**Issue by HFMS-LHB** [oxyplot/oxyplot-avalonia#26]
chinese characters unable to display in Chart Title and Series Title 
![image](https://user-images.githubusercontent.com/22726773/102952643-864b3f80-450a-11eb-892e-968e8e3b88b7.png)

avlaoniaui  v0.9.12

**Comment by kekekeks** [comment]
You need to use a font that has Chinese characters. https://github.com/anthonyfok/fonts-wqy-microhei is a good one
[WenQuanYiMicroHei-01.ttf.zip](https://github.com/AvaloniaUI/Avalonia/files/5703016/WenQuanYiMicroHei-01.ttf.zip)

Place it into `Assets`, add as `AvaloniaResource` and add something like 
```
<Style Selector="TextBlock">
    <Setter Property="FontFamily" Value="avares://YourAssemblyName/Assets/Fonts#WenQuanYi Micro Hei" />
</Style>
```
to your `App.xaml` after the theme

**Comment by HFMS-LHB** [comment]
> You need to use a font that has Chinese characters. https://github.com/anthonyfok/fonts-wqy-microhei is a good one
> [WenQuanYiMicroHei-01.ttf.zip](https://github.com/AvaloniaUI/Avalonia/files/5703016/WenQuanYiMicroHei-01.ttf.zip)
> 
> Place it into `Assets`, add as `AvaloniaResource` and add something like
> 
> ```
> <Style Selector="TextBlock">
>     <Setter Property="FontFamily" Value="avares://YourAssemblyName/Assets/Fonts#WenQuanYi Micro Hei" />
> </Style>
> ```
> 
> to your `App.xaml` after the theme

![image](https://user-images.githubusercontent.com/22726773/102978290-40f53500-453f-11eb-8be5-aed4ab914eba.png)
![image](https://user-images.githubusercontent.com/22726773/102978432-7732b480-453f-11eb-8b3f-784f37082431.png)

I did what you said.  After  tests ,font applied successfully
but it's not working ...   other textblock controls display normally.

**Comment by kekekeks** [comment]
Please check if that textblock has a proper font using devtools

**Comment by HFMS-LHB** [comment]
![image](https://user-images.githubusercontent.com/22726773/102980290-5324a280-4542-11eb-8cf3-84645c0cd603.png)

I set the `TitleFont`  property of `PlotModel` to make it display normally, the problem has been solved.
It looks like `Segoe UI` has a higher priority,new font do not get the highest priority. It's puzzling

**Comment by VisualMelon** [comment]
Related issue in the core library: https://github.com/oxyplot/oxyplot/issues/1469
