### ISSUE TITLE
LineStyle is not applied correctly

### ISSUE THREAD

**Issue by alessandrofrancesconi** [oxyplot/oxyplot-avalonia#30]
If you run LegendsDemo, you will see that line style (example "Dashed") is not applied to the whole line, but just to the start, then becomes "Solid".

![image](https://user-images.githubusercontent.com/1595223/117331452-0f9a5780-ae97-11eb-9372-5472e0a30c70.png)

**Comment by alessandrofrancesconi** [comment]
Same thing on Example Browser -> LineSeries -> LineStyle

![image](https://user-images.githubusercontent.com/1595223/117332460-268d7980-ae98-11eb-890b-ba43bd2e0173.png)

**Comment by VisualMelon** [comment]
Should be fixed by #31

**Comment by alessandrofrancesconi** [comment]
Fast as light!  :O
Will there be an updated NuGet package?

**Comment by VisualMelon** [comment]
I'm not sure who has the permission to do that, but it would seem a good time to push a new set targeting Avalonia 0.10.0.

**Comment by alessandrofrancesconi** [comment]
> I'm not sure who has the permission to do that, but it would seem a good time to push a new set targeting Avalonia 0.10.0.

By the way, Avalonia is now 0.10.3

**Comment by VisualMelon** [comment]
Releases for OxyPlot tend to be few and far between. You can always get the pre-releases packages: https://worldbeater.visualstudio.com/OxyPlot.Avalonia/_packaging?_a=feed&feed=OxyPlot.Avalonia-CI%40Local

**Comment by alessandrofrancesconi** [comment]
Didn't know about it, thanks
