### ISSUE TITLE
LineSeries has no 'ItemsSource' variable

### ISSUE THREAD

**Issue by ThaChillera** [oxyplot/oxyplot-avalonia#4]
I'm trying to port an application from WPF to Avalonia. But the Avalonia implementation of oxyplot's LineSeries object doesn't have an ItemsSource variable.

Has it been replaced with an alternative, is it not yet implemented, or something else?

Thanks for your help

**Comment by SuperLamic** [comment]
I know that it's an older issue, but the reason for this is that LineSeries is implemented both in OxyPlot.Avalonia and OxyPlot.Series. You need the latter. 

`using LineSeries = OxyPlot.Series.LineSeries;`

**Comment by VisualMelon** [comment]
In Avalonia, we use `Items` rather than `ItemsSource` in `Avalonia.Series` (inhereited from Avalonia's `ItemControl`, as was `ItemSource` from WPF).
