### ISSUE TITLE
Can't hide plost series while keeping the legend

### ISSUE THREAD

**Issue by yesod30** [oxyplot/oxyplot-avalonia#40]
I was trying to hide/unhide a series by double clicking on the relative legend text. I got to the point where i can get the series i want to hide, but setting the IsVisible property of the series to false seems to also remove it/hide it from the legend. This is a problem, sinceif the legend disappear, the user can't unhide the series anymore. Is there any way to do this in the current version?

**Comment by VisualMelon** [comment]
In the current version, I do not think this is viable.

The ability to hide series is built into OxyPlot 2.1.0, but we've not got around to releasing OxyPlot-Avalonia 2.1.0. See #38

**Comment by yesod30** [comment]
Yeah i saw that, was wondering if it was just a 2.1.0 feature or if i was missing something. Thanks for the confirmation, i'll wait for a release, you guys are doing a great job ^^
