### ISSUE TITLE
NullReferenceException when rendering annotations

### ISSUE THREAD

**Issue by colejohnson66** [oxyplot/oxyplot-avalonia#47]
Cross post from https://github.com/oxyplot/oxyplot/issues/1904

Appears to be an issue specifically with `OxyPlot.Avalonia`. @VisualMelon suggests two changes:

 - Calling `InvalidatePlot` off-thread should set a dirty-flag immediately, and schedule an update on the UI thread (not just crash)
 - `UpdateVisuals` should check the dirty-flag and perform an update if necessary before rendering

**Comment by VisualMelon** [comment]
Closing, as I believe this is fixed. Feel free to re-open/comment if you believe there is still an issue with this.
