### ISSUE TITLE
Does OxyPlot use System.Drawing?

### ISSUE THREAD

**Issue by sleytus2** [oxyplot/oxyplot-avalonia#50]
Newbie here...

We're developing a cross-platform Windows / MacOS app using Avalonia.  As you are probably aware Microsoft no longer supports cross-platform System.Drawing -- only Windows.  So, my question concerns whether OxyPlot is also tethered to System.Drawing or does it use something else, like SkiaSharp?

Thanks...

**Comment by VisualMelon** [comment]
OxyPlot-Avalonia uses the Avalonia visuals for rendering: it's not tied to any specific rendered, and I'm sure is not dependent on System.Drawing.

There is a System.Drawing exporter provision (https://www.nuget.org/packages/OxyPlot.Core.Drawing/) which shares code with the WinForms provision, so you may see references to it elsewhere in the core libraries, but shouldn't have anything to do with oxyplot-avalonia.

**Comment by sleytus2** [comment]
@VisualMelon -- wow, thanks for the quick response.  This is excellent news -- we'll be giving OxyPlot a try.
